### ISSUE TITLE
todo : game

### ISSUE THREAD

**Issue by svennd** [svennd/vita-chain#3]
- [x]  start with a information bubble
- [x]  end with a fail or inform bubble
- [x]  add levels 
- [x]  add complexity
- [x]  fix next level
- [x]  build win game over.
